### ISSUE TITLE
Error with namespace prefix t3

### ISSUE THREAD

**Issue by msollmann** [evoWeb/ew_llxml2xliff#10] opened 2022-02-15 18:02 UTC
When opening a record folder with records whose labels are converted to xliff the list module says:

> PHP Warning: simplexml_load_string(): namespace error : Namespace prefix t3 for id on file is not defined in /typo3_src-11.5.6/typo3/sysext/core/Classes/Localization/Parser/AbstractXmlParser.php line 116

Do we really need the t3:id attribute in the file node?
https://docs.typo3.org/m/typo3/reference-coreapi/main/en-us/ApiOverview/Internationalization/XliffFormat.html
https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-CoreApi/issues/1094

**Comment by garbast** [comment] 2022-02-16 08:55
Please test the develop branch, if the problem is fixed.

**Comment by msollmann** [comment] 2022-02-16 14:03
Great, it works!

**Comment by msollmann** [comment] 2022-06-01 17:26
Can you publish the new version? I forgot about the error and used the buggy TER version again, in another project...

**Comment by opi99** [comment] 2022-07-14 07:14
👍

**Comment by 720720** [comment] 2023-06-02 07:05
could you please publish the new version to the TER

**Comment by garbast** [comment] 2023-07-16 10:58
Released with tag 4.1

**Closed as completed by garbast** 2023-07-16 10:58 UTC
